# Generated by Django 4.0.4 on 2022-05-20 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gikians',
            fields=[
                ('reg_no', models.IntegerField(max_length=7, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('hash', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('year', models.IntegerField(max_length=1, unique=True)),
                ('faculty', models.CharField(max_length=10)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.university', unique=True)),
            ],
        ),
    ]
