# Generated by Django 4.0.4 on 2022-05-20 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gikians',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.university'),
        ),
        migrations.AlterField(
            model_name='gikians',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
