# Generated by Django 4.0.4 on 2022-06-02 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gikians',
            name='id',
        ),
        migrations.AlterField(
            model_name='giki_socities',
            name='reg_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.gikians'),
        ),
        migrations.AlterField(
            model_name='giki_teams',
            name='reg_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.gikians'),
        ),
        migrations.AlterField(
            model_name='gikians',
            name='reg_no',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mentee_interests',
            name='reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.gikians'),
        ),
        migrations.AlterField(
            model_name='mentees',
            name='mentor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_ids', to='main_web.gikians'),
        ),
        migrations.AlterField(
            model_name='mentees_of_mentors',
            name='men_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='men_ids', to='main_web.gikians'),
        ),
        migrations.AlterField(
            model_name='mentees_weak_courses',
            name='reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.gikians'),
        ),
        migrations.AlterField(
            model_name='mentor_best_courses',
            name='reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.gikians'),
        ),
        migrations.AlterField(
            model_name='mentor_skills',
            name='reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.gikians'),
        ),
    ]
