# Generated by Django 4.0.4 on 2022-05-21 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0003_alter_gikians_reg_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='main_web.gikians')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_creat', to='main_web.gikians')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=40)),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor_best_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_courses', models.CharField(max_length=40)),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Mentees_of_mentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.mentees')),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.mentor')),
            ],
        ),
        migrations.AddField(
            model_name='mentees',
            name='mentor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.mentor'),
        ),
        migrations.AddField(
            model_name='mentees',
            name='reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='main_web.gikians'),
        ),
        migrations.AddField(
            model_name='mentees',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.gikians'),
        ),
        migrations.CreateModel(
            name='Mentee_weak_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weak_courses', models.CharField(max_length=40)),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.mentees')),
            ],
        ),
        migrations.CreateModel(
            name='Mentee_interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.CharField(max_length=40)),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.mentees')),
            ],
        ),
        migrations.CreateModel(
            name='Giki_teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.CharField(max_length=30)),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.gikians')),
            ],
        ),
        migrations.CreateModel(
            name='Giki_societie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socities', models.CharField(max_length=30)),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.gikians')),
            ],
        ),
    ]
