# Generated by Django 4.0.4 on 2022-05-21 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0004_mentees_mentor_mentor_skills_mentor_best_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentees',
            name='reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_reg_derived_from_Gikian_models', to='main_web.gikians'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='reg_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_regno_derived_from_Gikians_Model', to='main_web.gikians'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_year_derived_from_Gikians_model', to='main_web.gikians'),
        ),
    ]
