# Generated by Django 4.0.4 on 2022-05-21 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0005_alter_mentees_reg_alter_mentor_reg_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giki_societie',
            name='id',
        ),
        migrations.AlterField(
            model_name='giki_societie',
            name='reg_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_web.gikians'),
        ),
    ]
