# Generated by Django 4.0.4 on 2022-05-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0006_remove_giki_societie_id_alter_giki_societie_reg_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gikians',
            options={'verbose_name_plural': 'Gikians'},
        ),
    ]
