# Generated by Django 4.0.4 on 2022-05-21 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0008_remove_gikians_id_alter_university_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gikians',
            name='id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_web.university'),
        ),
        migrations.AlterField(
            model_name='university',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
