# Generated by Django 4.0.4 on 2022-05-21 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0009_gikians_id_alter_university_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giki_teams',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mentee_interests',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mentee_weak_courses',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mentees',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mentees_of_mentors',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mentor_best_courses',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mentor_skills',
            name='id',
        ),
        migrations.AlterField(
            model_name='giki_teams',
            name='reg_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_web.gikians'),
        ),
        migrations.AlterField(
            model_name='mentee_interests',
            name='reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_web.mentees'),
        ),
        migrations.AlterField(
            model_name='mentee_weak_courses',
            name='reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_web.mentees'),
        ),
        migrations.AlterField(
            model_name='mentees',
            name='reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='%(class)s_reg_derived_from_Gikian_models', serialize=False, to='main_web.gikians'),
        ),
        migrations.AlterField(
            model_name='mentees_of_mentors',
            name='reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_web.mentor'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='reg_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='%(class)s_regno_derived_from_Gikians_Model', serialize=False, to='main_web.gikians'),
        ),
        migrations.AlterField(
            model_name='mentor_best_courses',
            name='reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_web.mentor'),
        ),
        migrations.AlterField(
            model_name='mentor_skills',
            name='reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_web.mentor'),
        ),
    ]
