# Generated by Django 4.0.4 on 2022-05-21 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0010_remove_giki_teams_id_remove_mentee_interests_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='year',
            field=models.ForeignKey(db_column='year', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_year_derived_from_Gikians_model', to='main_web.gikians'),
        ),
    ]
