# Generated by Django 4.0.4 on 2022-05-21 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0011_alter_mentor_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_year_derived_from_Gikians_model', to='main_web.gikians', to_field='year'),
        ),
    ]
