# Generated by Django 4.0.4 on 2022-05-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0013_alter_gikians_id_alter_mentees_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Giki_societie',
            new_name='Giki_societis',
        ),
    ]
